language: python

python:
  - 3.7

variables:
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

cache:
  key: pipenv
  paths:
    - .pipenv

install:
  - pip install --upgrade pipenv
  - pipenv install

branches:
  only:
    - master
    - stable

env:
  - DEBUG=False

script:
  - pipenv run pytest --flakes
