language: python

python:
  - 3.7

install:
  - pip install --upgrade pipenv
  - pipenv install

branches:
  only:
    - master
    - stable

env:
  - DEBUG=False

script:
  - pipenv run pytest --flakes
