language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
  dist: xenial
  sudo: true

install:
  - pip install --upgrade pipenv pytest
  - pipenv install

#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true

env:
  - DEBUG=False

script:
  - 'pipenv run pytest'
